contact_links:
  - name: 📃 Documentation
    url: https://github.com/kitadai31/revanced-patches-android6-7/wiki
    about: Don't know how or where to start? Check out our documentation!
  - name: 🗨 Discussions
    url: https://github.com/kitadai31/revanced-patches-android6-7/discussions
    about: This can be used for questions, suggestions, supports, announcements, etc. Search for or start a new discussion!